// Code generated by god. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/gotid/god/examples/http/jwt/internal/svc"

	"github.com/gotid/god/api"
)

func RegisterHandlers(server *api.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]api.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/token",
				Handler: JwtHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]api.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/info",
				Handler: GetUserHandler(serverCtx),
			},
		},
		api.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
