// Code generated by god. DO NOT EDIT!
// Source: graceful.proto

package server

import (
	"context"

	"github.com/gotid/god/example/graceful/dns/rpc/graceful"
	"github.com/gotid/god/example/graceful/dns/rpc/internal/logic"
	"github.com/gotid/god/example/graceful/dns/rpc/internal/svc"
)

type GracefulServiceServer struct {
	svcCtx *svc.ServiceContext
}

func NewGracefulServiceServer(svcCtx *svc.ServiceContext) *GracefulServiceServer {
	return &GracefulServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GracefulServiceServer) Grace(ctx context.Context, in *graceful.Request) (*graceful.Response, error) {
	l := logic.NewGraceLogic(ctx, s.svcCtx)
	return l.Grace(in)
}
