// Code generated by god. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/gotid/god/examples/shorturl/api/internal/svc"

	"github.com/gotid/god/api"
)

func RegisterHandlers(server *api.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]api.Route{
			{
				Method:  http.MethodGet,
				Path:    "/shorten",
				Handler: ShortenHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/expand",
				Handler: ExpandHandler(serverCtx),
			},
		},
	)
}
