// Code generated by god. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/gotid/god/example/graceful/dns/api/internal/svc"

	"github.com/gotid/god/api"
)

func RegisterHandlers(engine *api.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]api.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/graceful",
				Handler: GracefulHandler(serverCtx),
			},
		},
	)
}
