// Code generated by god. DO NOT EDIT.
// 源文件: transformer.proto

package server

import (
	"context"

	"github.com/gotid/god/examples/shorturl/rpc/transformer/internal/logic"
	"github.com/gotid/god/examples/shorturl/rpc/transformer/internal/svc"
	"github.com/gotid/god/examples/shorturl/rpc/transformer/transformer"
)

type TransformerServer struct {
	svcCtx *svc.ServiceContext
	transformer.UnimplementedTransformerServer
}

func NewTransformerServer(svcCtx *svc.ServiceContext) *TransformerServer {
	return &TransformerServer{
		svcCtx: svcCtx,
	}
}

func (s *TransformerServer) Shorten(ctx context.Context, in *transformer.ShortenRequest) (*transformer.ShortenResponse, error) {
	l := logic.NewShortenLogic(ctx, s.svcCtx)
	return l.Shorten(in)
}

func (s *TransformerServer) Expand(ctx context.Context, in *transformer.ExpandRequest) (*transformer.ExpandResponse, error) {
	l := logic.NewExpandLogic(ctx, s.svcCtx)
	return l.Expand(in)
}
