// Code generated by god. DO NOT EDIT!
// Source: graceful.proto

package main

import (
	"flag"
	"fmt"

	"github.com/gotid/god/example/graceful/dns/rpc/graceful"
	"github.com/gotid/god/example/graceful/dns/rpc/internal/config"
	"github.com/gotid/god/example/graceful/dns/rpc/internal/server"
	"github.com/gotid/god/example/graceful/dns/rpc/internal/svc"

	"github.com/gotid/god/lib/conf"
	"github.com/gotid/god/rpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/rpc.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	srv := server.NewGracefulServiceServer(ctx)

	s := rpc.MustNewServer(c.ServerConf, func(grpcServer *grpc.Server) {
		graceful.RegisterGracefulServiceServer(grpcServer, srv)
	})
	defer s.Stop()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
