// Code generated by god. DO NOT EDIT.
package types

type ShortenRequest struct {
	Url string `form:"url"`
}

type ShortenResponse struct {
	Shorten string `json:"shorten"`
}

type ExpandRequest struct {
	Shorten string `form:"shorten"`
}

type ExpandResponse struct {
	Url string `json:"url"`
}
